[metadata]
name = tkinterplus
version = attr: tkinterplus.__version__
author = Legopitstop
author_email=contact@lpsmods.dev
description=Tkinterplus is a python UI library that adds more widgets to Tkinter
keywords=tkinter,widgets,pygame,pillow
url=https://github.com/legopitstop/tkinterplus/
project_urls=
    Download=https://github.com/legopitstop/tkinterplus/releases
    Documentation=https://docs.lpsmods.dev/tkinterplus
    Source Code=https://github.com/legopitstop/tkinterplus
long_description=file: README.md
long_description_content_type=text/markdown
license=MIT
license_file=LICENSE
# Chose either "3 - Alpha", "4 - Beta" or "5 - Production/Stable" as the current state of your package
classifiers = 
    Development Status :: 5 - Production/Stable
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13

[options]
packages = tkinterplus
python_requires = >=3.13
install_requires =
    Pillow
    UserFolder
    pyyaml
    tkinter-tooltip
    accentcolordetect
    tkinter-tooltip
    colour
    tinycss
    pygame
    numpy
    requests
    python-dotenv
    easing_functions
    pyautogui
    soundfile
    pydantic
    tkcalendar
    emoji
    beautifulsoup4
    markdown
include_package_data = True

[options.package_data]
* = assets/**
