from datetime import datetime
import tkinter
import enum

from tkinterplus import EntryTypes
from tkinterplus.constants import *

root = tkinter.Tk()
root.title("Input")
root.minsize(500, 500)


class Items(enum.Enum):
    item1 = 1
    item2 = 2
    item3 = 3
    item4 = 4


def printValues():
    print("Color:", widget1.get())
    print("Short:", widget2.get())
    print("Password:", widget3.get())
    print("Integer:", widget4.get())
    print("File:", widget5.get())
    print("Diretory:", widget6.get())
    print("Keybind:", widget7.get())
    print("Float:", widget8.get())
    print("Text:", widget9.get())
    print("Email:", widget10.get())
    print("Tel:", widget11.get())
    print("Url:", widget12.get())
    print("Enum:", widget13.get())
    print("Date:", widget14.get())
    print("Datetime:", widget15.get())
    print("Month:", widget16.get())
    print("Time:", widget17.get())
    print("Week:", widget18.get())
    print("Radio:", widget19.get())
    print("Range:", widget20.get())


lbl1 = tkinter.Label(root, text="Color")
lbl2 = tkinter.Label(root, text="Short")
lbl3 = tkinter.Label(root, text="Password")
lbl4 = tkinter.Label(root, text="Integer")
lbl5 = tkinter.Label(root, text="File")
lbl6 = tkinter.Label(root, text="Diretory")
lbl7 = tkinter.Label(root, text="Keybind")
lbl8 = tkinter.Label(root, text="Float")
lbl9 = tkinter.Label(root, text="Text")
lbl10 = tkinter.Label(root, text="Email")
lbl11 = tkinter.Label(root, text="Tel")
lbl12 = tkinter.Label(root, text="Url")
lbl13 = tkinter.Label(root, text="Enum")
lbl14 = tkinter.Label(root, text="Date")
lbl15 = tkinter.Label(root, text="Datetime")
lbl16 = tkinter.Label(root, text="Month")
lbl17 = tkinter.Label(root, text="Time")
lbl18 = tkinter.Label(root, text="Week")
lbl19 = tkinter.Label(root, text="Radio")
lbl20 = tkinter.Label(root, text="Range")

widget1 = EntryTypes(root, COLOR, label=lbl1)
widget2 = EntryTypes(root, SHORT, label=lbl2)
widget3 = EntryTypes(root, PASSWORD, label=lbl3)
widget4 = EntryTypes(root, INTEGER, label=lbl4)
widget5 = EntryTypes(root, FILE, label=lbl5)
widget6 = EntryTypes(root, DIRECTORY, label=lbl6)
widget7 = EntryTypes(root, KEYBIND, label=lbl7)
widget8 = EntryTypes(root, FLOAT, label=lbl8)
widget9 = EntryTypes(root, TEXT, pattern=r"^[a-z]+$", label=lbl9, width=50, height=2)
widget10 = EntryTypes(root, EMAIL, label=lbl10)
widget11 = EntryTypes(root, TEL, label=lbl11)
widget12 = EntryTypes(root, URL, label=lbl12)
widget13 = EntryTypes(root, ENUM, label=lbl13, items=Items)
widget14 = EntryTypes(root, DATE, label=lbl14)
widget15 = EntryTypes(root, DATETIME, label=lbl15)
widget16 = EntryTypes(root, MONTH, label=lbl16)
widget17 = EntryTypes(root, TIME, label=lbl17)
widget18 = EntryTypes(root, WEEK, label=lbl18)
widget19 = EntryTypes(root, RADIO, label=lbl19)
widget20 = EntryTypes(root, RANGE, label=lbl20)

timestamp = datetime.today().timestamp()

widget1.set("#ff0000")
widget2.set("Short")
widget3.set("Password")
widget4.set(100)
widget5.set("C:/Users/1589l/Downloads/copper armor/copper_boots.png")
widget6.set("C:/Users/1589l/Downloads/copper armor")
widget7.set("<Control-k>")
widget8.set(0.5)
widget9.set("Long")
widget10.set("example@gmail.com")
widget11.set("123-456-7890")
widget12.set("https://example.com")
widget13.set(Items.item1)
widget14.set(timestamp)
widget15.set(timestamp)
widget16.set(timestamp)
widget17.set(timestamp)
widget18.set(timestamp)
widget19.set(True)
widget20.set(50)

lbl1.grid(row=0, column=0)
lbl2.grid(row=1, column=0)
lbl3.grid(row=2, column=0)
lbl4.grid(row=3, column=0)
lbl5.grid(row=4, column=0)
lbl6.grid(row=5, column=0)
lbl7.grid(row=6, column=0)
lbl8.grid(row=7, column=0)
lbl9.grid(row=8, column=0)
lbl10.grid(row=9, column=0)
lbl11.grid(row=10, column=0)
lbl12.grid(row=11, column=0)
lbl13.grid(row=12, column=0)
lbl14.grid(row=13, column=0)
lbl15.grid(row=14, column=0)
lbl16.grid(row=15, column=0)
lbl17.grid(row=16, column=0)
lbl18.grid(row=17, column=0)
lbl19.grid(row=18, column=0)
lbl20.grid(row=19, column=0)

widget1.grid(row=0, column=1, sticky=tkinter.W)
widget2.grid(row=1, column=1, sticky=tkinter.W)
widget3.grid(row=2, column=1, sticky=tkinter.W)
widget4.grid(row=3, column=1, sticky=tkinter.W)
widget5.grid(row=4, column=1, sticky=tkinter.W)
widget6.grid(row=5, column=1, sticky=tkinter.W)
widget7.grid(row=6, column=1, sticky=tkinter.W)
widget8.grid(row=7, column=1, sticky=tkinter.W)
widget9.grid(row=8, column=1, sticky="nesw")
widget10.grid(row=9, column=1, sticky=tkinter.W)
widget11.grid(row=10, column=1, sticky=tkinter.W)
widget12.grid(row=11, column=1, sticky=tkinter.W)
widget13.grid(row=12, column=1, sticky=tkinter.W)
widget14.grid(row=13, column=1, sticky=tkinter.W)
widget15.grid(row=14, column=1, sticky=tkinter.W)
widget16.grid(row=15, column=1, sticky=tkinter.W)
widget17.grid(row=16, column=1, sticky=tkinter.W)
widget18.grid(row=17, column=1, sticky=tkinter.W)
widget19.grid(row=18, column=1, sticky=tkinter.W)
widget20.grid(row=19, column=1, sticky=tkinter.W)

tkinter.Button(root, text="Print Values", command=printValues).grid(row=20, column=0)

# responsive
root.grid_rowconfigure(1, weight=1)
root.grid_columnconfigure(1, weight=1)
root.configure(padx=5, pady=5)

root.mainloop()
